### ISSUE TITLE
[WEBJS] - /api/sendImage fails with "msg.avParams is not a function"

### ISSUE THREAD

**Issue by lorenzo-bb** [devlikeapro/waha#2149]
### Describe the bug

Sending an image via POST /api/sendImage fails with a 500 error. Text-only messages via /api/sendText work fine on the same session; only messages that include media fail.

### Version

```
"version": "2026.6.2",
"engine": "WEBJS",
"tier": "PLUS",
"browser": "/usr/bin/chromium",
"platform": "linux/x64"
```

## Steps

**To Reproduce** Steps to reproduce the behavior:

1. Run WAHA with `WHATSAPP_DEFAULT_ENGINE=WEBJS`, version `2026.6.2`.
2. Start and authenticate a session (QR pairing).
3. Send a `POST /api/sendImage` request:

```json
{
  "chatId": "***",
  "file": {
    "mimetype": "image/jpeg",
    "filename": "filename.jpg",
    "url": "https://***"
  },
  "reply_to": null,
  "caption": "Lorem ipsum ...",
  "session": "***"
}
```

4. Observe the 500 response below.

### Error Response

```json
{
  "statusCode": 500,
  "timestamp": "2026-07-08T09:07:46.116Z",
  "exception": {
    "message": "msg.avParams is not a function",
    "name": "TypeError",
    "stack": "TypeError: msg.avParams is not a function\nwindow.WWebJS.sendMessage (pptr:evaluate;WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:36):533:50)\n    at window.WWebJS.sendMessage (evaluate at WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:36), <anonymous>:532:49)\n    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:391:56)\n    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:277:16)\n    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)\n    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:362:20)\n    at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:818:20)\n    at async WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:20)\n    at async WebjsClientCore.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:1616:25)\n    at async descriptor.value (/app/dist/core/abc/activity.js:9:20)"
  },
  "request": {
    "path": "/api/sendImage",
    "method": "POST"
  }
}
```

### Expected behavior

The image should send successfully, as it did before updating.

### Troubleshooting already done

- Downgraded to previous installed version `2026.5.1` - same error persisted.
- Logged out and re-paired the session via QR from scratch on `2026.5.1` - same error persisted.
- Upgraded back to latest (`2026.6.2`) - same error.
- Text-only messages (`/api/sendText`) work correctly throughout.

Since the error persists across two WAHA versions and a fresh session pairing, this looks like it's caused by a change on WhatsApp Web's side (the live web.whatsapp.com client that Puppeteer loads).

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
**Let's try dev image** 🤞🏻

Make sure to select the [**engine**](https://waha.devlike.pro/docs/how-to/engines/) via the environment variable - `WHATSAPP_DEFAULT_ENGINE=WEBJS`:

-   `devlikeapro/waha-plus:dev`
-   `devlikeapro/waha-plus:dev-chrome`
-   `devlikeapro/waha-plus:dev-arm`

🚀 Will be included in the next release!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Globerada** [comment]
Same error here.

**Comment by danielmwxx** [comment]
> **Let's try dev image** 🤞🏻
> 
> Make sure to select the [**engine**](https://waha.devlike.pro/docs/how-to/engines/) via the environment variable - `WHATSAPP_DEFAULT_ENGINE=WEBJS`:
> 
> * `devlikeapro/waha-plus:dev`
> * `devlikeapro/waha-plus:dev-chrome`
> * `devlikeapro/waha-plus:dev-arm`
> 
> 🚀 Will be included in the next release!
> 
> [![patron:PRO](https://camo.githubusercontent.com/f603a6a99a2dbd219edd08c5cfb2b5edf01581c2e2e5e21a5d50298508c04a6f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

The dev image requires a password, but it is no longer possible to subscribe to Plus to obtain it.

**Comment by RabbiArt** [comment]
I have the same error as mentioned by @lorenzo-bb

**Comment by devlikepro** [comment]
`2026.7.1` - **WEBJS** - sending an image fails with `msg.avParams is not a function` - [#2149](https://github.com/devlikeapro/waha/issues/2149)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by lorenzo-bb** [comment]
I confirm the issue has been solved after update to 2026.7.1

Thank you very much to devlikepro team for the prompt fix!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
